app/goal_tracker/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import register_user, update_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('my_habits/', include('habits.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', next_page='pages:home'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', register_user, name='register'),
    path('update_user/', update_user, name='update-user'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

app/habits/urls.py
from django.urls import path

from . import views


app_name = 'habits'
urlpatterns = [
    path('list/', views.list_habits, name='list'),
    path('create/', views.create_habit, name='create'),
    path('update/<int:pk>/', views.update_habit, name='update'),
    path('reset/<int:pk>/', views.reset_habit, name='reset'),
    path('delete/<int:pk>/', views.delete_habit, name='delete'),
]

app/pages/urls.py
from django.urls import path

from . import views


app_name = 'pages'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

app/goal_tracker/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

app/goal_tracker/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm


def register_user(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Witaj {username}! Twoje konto zostało utworzone. Możesz się teraz zalogować.')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', context={'form': form})


@login_required(login_url='login')
def update_user(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Twój profil został zaktualizowany.')
            return redirect('update-user')
    else:
        form = UserUpdateForm(instance=request.user)
    return render(request, 'users/update.html', context={'form': form})

app/goal_tracker/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="h-100">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'goal_tracker/base.css' %}">

    <title>GoalsTracker.pl</title>
</head>

{% block body %}
{% endblock body %}

</html>

app/goal_tracker/templates/body.html
{% extends 'base.html' %}
{% block body %}
<body class="h-100 bg-dark">
    {% include "header.html" %}
    <main class="min-vh-100 bg-light">
        <div class="container h-100">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    {% include "footer.html" %}

<!--JavaScript Bootstrap Bundle with Popper-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
{% endblock body %}

app/goal_tracker/templates/body_cover.html
{% extends 'base.html' %}
{% block body %}
<body class="d-flex flex-column justify-content-between h-100 bg-dark">

    {% include "header.html" %}

    {% block main %}
    {% endblock main %}

    {% include "footer.html" %}

<!--JavaScript Bootstrap Bundle with Popper-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
{% endblock body %}

app/goal_tracker/templates/footer.html
    <footer class="footer text-light text-center">
        <div class="container">
            <p class="fw-lighter pt-3">©2024 Tomasz Wiaderek</p>
        </div>
    </footer>

app/goal_tracker/templates/header.html
    <header class="p-3">
        <div class="container">
            <nav class="navbar navbar-expand-lg justify-content-center">
                <div class="float-md-start">
                    <a class="navbar-brand link-light" href="{% url 'pages:home' %}">GoalsTracker</a>
                </div>
                <div class="nav justify-content-center float-md-end" id="navbarNav">
                    <a class="nav-link link-light" href="{% url 'pages:about' %}">About</a>
                    {% if user.is_authenticated %}
                    <a class="nav-link link-light" href="{% url 'habits:list' %}">My habits</a>
                    <a class="nav-link link-light" href="{% url 'update-user' %}">My profile</a>
                    <a class="nav-link link-light" href="{% url 'logout' %}">Log out</a>
                    {% else %}
                    <a class="nav-link link-light" href="{% url 'login' %}">Login</a>
                    <a class="nav-link link-light" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </nav>
        </div>
    </header>