app/goal_tracker/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from .views import register_user, update_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('my_habits/', include('habits.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', next_page='pages:home'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', register_user, name='register'),
    path('update_user/', update_user, name='update-user'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

app/habits/urls.py
from django.urls import path

from . import views


app_name = 'habits'
urlpatterns = [
    path('list/', views.list_habits, name='list'),
    path('create/', views.create_habit, name='create'),
    path('update/<int:pk>/', views.update_habit, name='update'),
    path('reset/<int:pk>/', views.reset_habit, name='reset'),
    path('delete/<int:pk>/', views.delete_habit, name='delete'),
]

app/pages/urls.py
from django.urls import path

from . import views


app_name = 'pages'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

app/habits/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

from .initials import init_list


class Sentance(models.Model):
    content = models.CharField(max_length=256)

    def __str__(self):
        return self.content


class Habit(models.Model):
    name = models.CharField(max_length=128)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    reason = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_abstynance_time(self):
        return now() - self.start_date

    def get_current_milestone(self):
        return Milestone.objects.get(habit__pk=self.pk, is_active=True)

    def get_all_milestones(self):
        return Milestone.objects.filter(habit__pk=self.pk).order_by('req_abstynence_time')

    def get_all_achieved_milestones(self):
        return Milestone.objects.filter(habit__pk=self.pk, is_achieved=True).order_by('req_abstynence_time')

    def init_milestones(self):
        for m in init_list:
            Milestone.objects.create(name=m.get('name'),
                                     req_abstynence_time=m.get('req_abstynence_time'),
                                     is_active=m.get('is_active'),
                                     habit=self)

    def delete_all_milestones(self):
        self.get_all_milestones().delete()

    def scan_and_update_milestones(self):
        milestones = self.get_all_milestones()
        for m in range(0, len(milestones)):
            milestones[m].update_status()
            if milestones[m].is_achieved and m < len(milestones) - 1:
                milestones[m + 1].is_active = True
                milestones[m + 1].save()


class Milestone(models.Model):
    name = models.CharField(max_length=128)
    req_abstynence_time = models.DurationField(null=True)
    is_achieved = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    date_finished = models.DateTimeField(null=True, blank=True)
    habit = models.ForeignKey(Habit, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def update_status(self):
        end_date = self.habit.start_date + self.req_abstynence_time
        if now() > end_date:
            self.is_achieved = True
            self.is_active = False
            self.date_finished = end_date
            self.save()

app/habits/forms.py
from django import forms
from .models import Habit


class HabitCreateForm(forms.ModelForm):
    name = forms.CharField(strip=True)
    start_date = forms.DateTimeField(
        widget=forms.DateTimeInput(format='%Y-%m-%d %H:%M', attrs={'placeholder': 'YYYY-MM-DD HH:MM'}))
    reason = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 1, 'cols': 20}))

    class Meta:
        model = Habit
        fields = ['name', 'start_date', 'reason']


class HabitUpdateForm(forms.ModelForm):
    name = forms.CharField(strip=True)
    reason = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 1, 'cols': 20}))

    class Meta:
        model = Habit
        fields = ['name', 'reason']


class HabitResetForm(forms.ModelForm):
    start_date = forms.DateTimeField(
        widget=forms.DateTimeInput(format='%Y-%m-%d %H:%M', attrs={'placeholder': 'YYYY-MM-DD HH:MM'}))

    class Meta:
        model = Habit
        fields = ['start_date']

app/habits/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Habit
from .forms import HabitCreateForm, HabitUpdateForm, HabitResetForm


@login_required(login_url='login')
def list_habits(request):
    habits = Habit.objects.filter(owner=request.user).order_by('start_date')
    for h in habits:
        h.scan_and_update_milestones()
    return render(request, template_name='habits/list.html', context={'objects': habits})


@login_required(login_url='login')
def create_habit(request):
    if request.method == 'POST':
        form = HabitCreateForm(request.POST)
        if form.is_valid():
            form.cleaned_data['owner'] = request.user
            habit = Habit.objects.create(**form.cleaned_data)
            habit.save()
            habit.init_milestones()
            habit.scan_and_update_milestones()
            return redirect(reverse('habits:list'))
    else:
        form = HabitCreateForm()
    return render(request, template_name='habits/create.html', context={'form': form})


@login_required(login_url='login')
def update_habit(request, pk):
    habit = get_object_or_404(Habit, pk=pk)
    if habit.owner == request.user:
        if request.method == 'POST':
            form = HabitUpdateForm(request.POST, instance=habit)
            if form.is_valid():
                form.save()
                return redirect(reverse('habits:list'))
        else:
            form = HabitUpdateForm(instance=habit)
    else:
        return redirect('login')
    return render(request, template_name='habits/update.html', context={'form': form})


@login_required(login_url='login')
def delete_habit(request, pk):
    habit = get_object_or_404(Habit, pk=pk)
    if habit.owner == request.user:
        if request.method == 'POST':
            habit.delete()
            return redirect(reverse('habits:list'))
    else:
        return redirect('login')
    return render(request, template_name='habits/delete.html', context={'object': habit})


@login_required(login_url='login')
def reset_habit(request, pk):
    habit = get_object_or_404(Habit, pk=pk)
    if habit.owner == request.user:
        if request.method == 'POST':
            form = HabitResetForm(request.POST, instance=habit)
            if form.is_valid():
                form.save()
                habit.delete_all_milestones()
                habit.init_milestones()
                habit.scan_and_update_milestones()
                return redirect(reverse('habits:list'))
        else:
            form = HabitResetForm(instance=habit)
    else:
        return redirect('login')
    return render(request, template_name='habits/reset.html', context={'form': form})

app/habits/templates/habits/create.html
{% extends 'body.html' %}
{% block content %}
                <h4 class="py-3">Add the habit you want to break with</h4>
                <form method="post" action="{% url 'habits:create' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <fieldset class="pt-3">
                        <button type="submit" class="btn btn-primary">Add</button>
                        <button type="reset" class="btn btn-outline-secondary">Clear</button>
                        <a href="{% url 'habits:list' %}" class="btn btn-secondary">Cancel</a>
                    </fieldset>
                </form>
{% endblock %}

app/habits/templates/habits/delete.html
{% extends 'body.html' %}
{% block content %}
                <form method="post">
                    {% csrf_token %}
                    <h4 class="py-3">Delete habit</h4>
                    <h5>Are you sure you want to remove the habit: {{ object.name }}?</h5>
                    <fieldset class="pt-3">
                        <button type="submit" class="btn btn-danger">Delete</button>
                        <a href="{% url 'habits:update' object.pk %}" class="btn btn-secondary">Cancel</a>
                    </fieldset>
                </form>
{% endblock %}

app/habits/templates/habits/list.html
{% extends 'body.html' %}
{% block content %}
            <section class="py-5 text-center container">
                <div class="row py-lg-5">
                    <div class="col-lg-6 col-md-8 mx-auto">
                        <figure>
                            <blockquote class="blockquote">
                                <h1 class="h3 fw-light">"The bad news is time flies. The good news is you're the pilot."</h1>
                            </blockquote>
                            <figcaption class="blockquote-footer">
                                Michael Altshuler
                            </figcaption>
                        </figure>
                        <p class="lead text-body-secondary">My bad habits</p>
                        <a href="{% url 'habits:create' %}" class="btn btn-primary my-2">Add new</a>
                    </div>
                </div>
            </section>

            <div class="album py-5 bg-body-tertiary">
                <div class="container">
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% if objects %}
                    {% for obj in objects %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                                    <title>Placeholder</title>
                                    <rect width="100%" height="100%" fill="#55595c"/>
                                    <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ obj.name }}</text>
                                </svg>
                                <div class="card-body">
                                    <p class="card-text">{{ obj.reason }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{% url 'habits:update' obj.pk %}" class="btn btn-sm btn-primary">Update</a>
                                        </div>
                                    <small class="text-body-secondary mx-3">Time of abstynence: {{ obj.get_abstynance_time }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% else %}
                    <p>You haven't identified any bad habits yet.</p>
                    {% endif %}
                    </div>
                </div>
            </div>
{% endblock content %}

app/habits/templates/habits/reset.html
{% extends 'body.html' %}
{% block content %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h4 class="py-3">Time of abstynence:</h4>
                    <p>{{ form.instance.get_abstynance_time }}</p>
                    <h4 class="py-3">Set new start date</h4>
                    {{ form.as_p }}
                    <small>Note that all your achieved milestones will be reset as well.</small>
                    <fieldset class="pt-3">
                        <button type="submit" class="btn btn-primary">Save changes</button>
                        <a href="{% url 'habits:list' %}" class="btn btn-secondary">Cancel</a>
                    </fieldset>
                </form>
{% endblock content %}

app/habits/templates/habits/update.html
{% extends 'body.html' %}
{% block content %}
                <form method="post" enctype="multipart/form-data">
                    <h4 class="py-3">Details of your habit:</h4>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <h4 class="py-3">Time of abstynence:</h4>
                    <p>{{ form.instance.get_abstynance_time }}</p>
                    <a href="{% url 'habits:reset' form.instance.pk %}" class="btn btn-warning">Reset time</a>
                    <h4 class="py-3">Your milestones:</h4>
                    <dl>
                        <dt>Achieved:</dt>
                        {% for m in form.instance.get_all_achieved_milestones %}
                            <dd>{{ m }}</dd>
                        {% endfor %}
                        <dt>Current goal:</dt>
                        {{ form.instance.get_current_milestone }}
                    </dl>
                    <fieldset class="pt-3">
                        <button type="submit" class="btn btn-primary">Save changes</button>
                        <a href="{% url 'habits:list' %}" class="btn btn-secondary">Cancel</a>
                        <a href="{% url 'habits:delete' form.instance.pk %}" class="btn btn-danger">Delete</a>
                    </fieldset>
                </form>
{% endblock content %}